{{- if eq .Values.config.pg.create true -}}
apiVersion: v1
kind: Secret
metadata:
  name: pg-service-conf-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  pg_service_conf: {{  .Values.config.pg.conf | b64enc }}
{{- end -}}
