# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.3.24/c2cciutils/schema.json

checks:
  required_workflows:
    clean.yaml: false
    audit.yaml: false
    backport.yaml: false
    codeql.yaml: false
  black:
    ignore_patterns_re:
      - .*\.yaml
  codespell:
    ignore_re:
      - \.github/workflows/pull-request-automation\.yaml
